 export let alpha = [
  "A","B","C","D","E","F","G","H","I","J",
  "K","L","M","N","O","P","Q","R","S","T",
  "U","V","W","X","Y","Z"
];

export let questions = [
{ qns:"The collection of elements is called?", answer:"ARRAY" },
{ qns:"FIFO data structure?", answer:"QUEUE" },
{ qns:"LIFO data structure?", answer:"STACK" },
{ qns:"Binary tree top node?", answer:"ROOT" },
{ qns:"Smallest data unit?", answer:"BIT" },
{ qns:"Eight bits equal?", answer:"BYTE" },
{ qns:"Temporary memory?", answer:"RAM" },
{ qns:"Permanent memory?", answer:"ROM" },
{ qns:"Brain of computer?", answer:"CPU" },
{ qns:"Keyword to stop loop?", answer:"BREAK" },
{ qns:"Keyword to skip loop?", answer:"CONT" },
{ qns:"Database query language?", answer:"SQL" },
{ qns:"Web structure language?", answer:"HTML" },
{ qns:"Web styling language?", answer:"CSS" },
{ qns:"Web scripting language?", answer:"JS" },
{ qns:"Android native language?", answer:"KOTLIN" },
{ qns:"iOS native language?", answer:"SWIFT" },
{ qns:"Popular AI language?", answer:"PYTHON" },
{ qns:"Microsoft dot net language?", answer:"CSHARP" },
{ qns:"OOP concept hiding data?", answer:"ENCAP" },
{ qns:"OOP feature many forms?", answer:"POLY" },
{ qns:"OOP child parent concept?", answer:"INHERIT" },
{ qns:"Time complexity notation?", answer:"BIGO" },
{ qns:"Fast search in sorted array?", answer:"BINARY" },
{ qns:"Simple sorting method?", answer:"BUBBLE" },
{ qns:"Operating system example?", answer:"LINUX" },
{ qns:"Version control tool?", answer:"GIT" },
{ qns:"Container platform?", answer:"DOCKER" },
{ qns:"Secure web protocol?", answer:"HTTPS" },
{ qns:"Network protocol suite?", answer:"TCPIP" },
{ qns:"Node based data structure?", answer:"LINKED" },
{ qns:"Array first index?", answer:"ZERO" },
{ qns:"True false data type?", answer:"BOOL" },
{ qns:"Decimal number type?", answer:"FLOAT" },
{ qns:"Whole number type?", answer:"INT" },
{ qns:"Function returning nothing?", answer:"VOID" },
{ qns:"Memory allocation in C?", answer:"MALLOC" },
{ qns:"Print function in C?", answer:"PRINTF" },
{ qns:"Java virtual machine?", answer:"JVM" },
{ qns:"Python function keyword?", answer:"DEF" },
{ qns:"Frontend library by Meta?", answer:"REACT" },
{ qns:"Frontend framework by Google?", answer:"ANGULAR" },
{ qns:"Mobile SDK by Google?", answer:"FLUTTER" },
{ qns:"Database unique key?", answer:"PRIMARY" },
{ qns:"Function calling itself?", answer:"RECUR" },
{ qns:"OS core component?", answer:"KERNEL" },
{ qns:"Cyber attack trick?", answer:"PHISH" },
{ qns:"AI subset?", answer:"ML" },
{ qns:"Network directing device?", answer:"ROUTER" },
{ qns:"Internet connecting device?", answer:"MODEM" },
{ qns:"Software development model?", answer:"AGILE" },
{ qns:"Testing smallest code unit?", answer:"UNIT" },
{ qns:"API style?", answer:"REST" },
{ qns:"Program error?", answer:"BUG" },
{ qns:"Fixing errors process?", answer:"DEBUG" },
{ qns:"Command line short form?", answer:"CLI" },
{ qns:"Depth first traversal?", answer:"DFS" },
{ qns:"Breadth first traversal?", answer:"BFS" },
{ qns:"Local variable memory?", answer:"STACK" },
{ qns:"Dynamic memory area?", answer:"HEAP" },
{ qns:"Keyword create object Java?", answer:"NEW" },
{ qns:"Java import keyword?", answer:"IMPORT" },
{ qns:"C++ output object?", answer:"COUT" },
{ qns:"Python package manager?", answer:"PIP" },
{ qns:"Code hosting platform?", answer:"GITHUB" },
{ qns:"Loop with counter?", answer:"FOR" },
{ qns:"Condition checking loop?", answer:"WHILE" },
{ qns:"Binary number base?", answer:"TWO" },
{ qns:"Decimal number base?", answer:"TEN" },
{ qns:"Hexadecimal base?", answer:"SIXTEEN" },
{ qns:"Popular NoSQL database?", answer:"MONGO" },
{ qns:"Relational database example?", answer:"MYSQL" },
{ qns:"IDE by Microsoft?", answer:"VSCODE" },
{ qns:"Python input function?", answer:"INPUT" },
{ qns:"Encryption algorithm?", answer:"AES" },
{ qns:"Public key algorithm?", answer:"RSA" },
{ qns:"Blockchain unit?", answer:"BLOCK" },
{ qns:"Parallel execution concept?", answer:"THREAD" },
{ qns:"Hide implementation detail?", answer:"ABSTRACT" },
{ qns:"Logical AND symbol?", answer:"AND" },
{ qns:"Logical OR symbol?", answer:"OR" },
{ qns:"Logical NOT symbol?", answer:"NOT" },
{ qns:"Malicious software?", answer:"MALWARE" },
{ qns:"Network security layer?", answer:"SSL" },
{ qns:"Search engine example?", answer:"GOOGLE" },
{ qns:"Backend Java framework?", answer:"SPRING" },
{ qns:"Code to machine process?", answer:"COMPILE" }
];